# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android
 
trigger:
- master
 
pool:
vmImage: 'macos-latest'
 
steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleDebug'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: 'Test2000'
    appSlug: 'gron0005/Vitality'
    appFile: '$(build.artifactStagingDirectory)'
    releaseNotesOption: 'input'
    releaseNotesInput: 'rel'

